name: Build Calorie counter CI

on: [push]

jobs:
  build_ci:
    strategy:
      matrix:
        os:   [ubuntu-latest, windows-latest]
        java: [ 8, 11 ]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    name: Build calorie counter CI ${{ matrix.os }} on Java ${{ matrix.java }} 

    steps:
    - uses: actions/checkout@v2
      with:
        path: recepts_rebuild_var_2


    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    
    - name: Grant execute permission for gradlew (*nix or MacOS)
      working-directory: recepts_rebuild_var_2
      run: chmod +x gradlew
      if: runner.os != 'Windows'
      
    - name: Build with Gradle
      working-directory: recepts_rebuild_var_2
      run: ./gradlew build --stacktrace --scan
